"""The explicitly-labelled development inference path.

PART 29 requires the backend to be usable locally without IBM credentials, and the
existing test suite exercises a ``is_mock`` flag that predates the trained model. This
module is what that flag reaches. It exists so that:

* the Flutter client can be developed against a running backend before any model has
  been trained, and
* a contributor who clones the repository without the dataset still gets a working
  ``POST /api/screening/analyze``.

What it is not
--------------
It is not a fallback. :class:`~backend.services.inference_service.InferenceService`
never delegates here when artifacts are missing -- that case returns 503. A caller
gets a mock result only by asking for one, and every mock result is labelled in three
independent places: ``is_mock=True``, ``MOCK`` in the risk level, and ``TEST DATA`` in
the details text. The FINAL EXECUTION RULE forbids a backend that quietly returns
fabricated clinical results; a loudly-labelled development stub asked for by name is a
different thing, and the labelling is what makes it so.

Determinism
-----------
The score is a hash of the request, not a random draw. The same payload always yields
the same mock result, so a UI developer can rely on a stable value, and a test can
assert on it. It is derived from the request only -- it has no relationship to the
image content and carries no predictive meaning whatsoever.
"""

from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone
from typing import Optional

from backend.core.config import Settings, settings as default_settings
from backend.schemas.inference import (
    CalibrationSummary,
    FeatureSummary,
    InferenceResult,
    QuantumSummary,
)
from quantum_ml.calibration import ProbabilityCalibrator

MOCK_MODEL_VERSION = "mock-development"
MOCK_NOTICE = (
    "SIMULATED TEST DATA. This result was generated by the development stub, not by "
    "the screening model. It has no clinical meaning."
)


def _deterministic_score(seed_material: str) -> float:
    """Map a request to a stable score in [0.02, 0.98].

    A hash rather than a PRNG so the value is reproducible across processes and
    Python versions, which ``random`` with a seeded state is not guaranteed to be.
    """
    digest = hashlib.sha256(seed_material.encode("utf-8")).digest()
    fraction = int.from_bytes(digest[:8], "big") / float(1 << 64)
    return 0.02 + fraction * 0.96


def mock_inference(
    *,
    seed_material: str,
    config: Optional[Settings] = None,
) -> InferenceResult:
    """Build a fully-formed but clearly-labelled development result.

    Args:
        seed_material: any stable string from the request -- an image path, a patient
            pseudonym plus scan type. Determines the score.
        config: settings supplying the fallback band boundaries.

    Returns:
        An :class:`InferenceResult` with ``is_mock=True``. The risk level carries a
        ``MOCK`` prefix and the details carry ``TEST DATA``, both applied by
        :meth:`ProbabilityCalibrator.categorize_risk`.
    """
    cfg = config or default_settings
    bands = ProbabilityCalibrator.from_settings(cfg)
    score = _deterministic_score(seed_material)
    risk_level, classification, details = bands.categorize_risk(
        probability=score, is_mock=True
    )
    return InferenceResult(
        inference_id=str(uuid.uuid4()),
        model_version=MOCK_MODEL_VERSION,
        created_at=datetime.now(timezone.utc),
        probability=score,
        probability_uncalibrated=score,
        raw_score=score,
        expectation_value=1.0 - 2.0 * score,
        risk_level=risk_level,
        classification=classification,
        details=details,
        calibration=CalibrationSummary(
            method="none",
            is_calibrated=False,
            fitted_on="",
            screening_threshold=bands.threshold,
            high_risk_threshold=bands.high_risk_threshold,
            bands_source="mock",
        ),
        quantum=QuantumSummary(
            # Zeros rather than plausible-looking values: no circuit was built, and a
            # response claiming 8 qubits would be a small lie in an audit record.
            n_qubits=0,
            circuit_depth=0,
            n_ansatz_layers=0,
            n_parameters=0,
            amplitude_dimension=0,
            execution_mode="mock",
            backend_name="none",
            shots=None,
            requested_mode=cfg.QUANTUM_EXECUTION_MODE,
            is_exact=False,
        ),
        features=FeatureSummary(feature_mode="mock", extractor="none"),
        quality=None,
        execution_time_ms=0.0,
        quantum_time_ms=0.0,
        preprocessing_time_ms=0.0,
        is_mock=True,
    )
