"""Load cached features into fitted, split-respecting partition matrices.

Every training and evaluation entry point needs the same six steps: read the
feature cache, read the split manifest, attach labels, attach clinical rows, fit
the pipeline, transform each partition. Duplicating that in five scripts is how
the fitting discipline gets broken -- one script fits on the wrong rows and
nothing complains.

So it lives here once, and :func:`load_partitions` is the only supported way to
get a matrix. It fits on ``train`` and nothing else, and it raises if the manifest
and the cache disagree.

Leakage guard
-------------
:func:`load_partitions` re-checks patient-level separation on every call, not just
in the test suite. The manifest is verified when written and verified again when
read: an artifact copied between machines, or regenerated by hand, cannot quietly
introduce a patient that spans partitions.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np

from backend.core.config import Settings, settings as default_settings
from backend.dataset.smartom import ImageRecord, SmartOmIndex, build_index
from backend.dataset.split import SplitManifest, binary_label
from backend.ml.artifacts import ArtifactStore
from backend.ml.pipeline import ClassicalPipeline, build_pipeline
from backend.training.prepare_dataset import clinical_row_for, load_feature_cache

logger = logging.getLogger(__name__)

PARTITIONS: Tuple[str, str, str] = ("train", "validation", "test")


class PartitionError(RuntimeError):
    """Raised when the cache, the manifest, and the index cannot be reconciled."""


@dataclass
class Partition:
    """One partition's aligned arrays."""

    name: str
    image_ids: List[str]
    patient_ids: List[str]
    labels: np.ndarray
    """Binary labels, positive = OPMD or oral cancer."""
    image_features: np.ndarray
    """Raw cached descriptors, ``(n, d_image)``. Pre-fusion, pre-reduction."""
    clinical_rows: List[Optional[Mapping[str, Any]]]
    diagnostic_classes: List[str]
    features: Optional[np.ndarray] = None
    """Fused and reduced matrix, ``(n, d_reduced)``. Populated by the loader."""

    @property
    def n(self) -> int:
        return len(self.image_ids)

    @property
    def n_positive(self) -> int:
        return int(np.sum(self.labels == 1))

    @property
    def prevalence(self) -> float:
        return float(np.mean(self.labels)) if self.n else 0.0

    @property
    def n_patients(self) -> int:
        return len(set(self.patient_ids))

    def summary(self) -> Dict[str, Any]:
        return {
            "partition": self.name,
            "n_images": self.n,
            "n_patients": self.n_patients,
            "n_positive": self.n_positive,
            "n_negative": self.n - self.n_positive,
            "prevalence": round(self.prevalence, 4),
            "n_reduced_features": None if self.features is None else int(self.features.shape[1]),
        }


@dataclass
class LoadedDataset:
    """Fitted pipeline plus the three transformed partitions."""

    pipeline: ClassicalPipeline
    partitions: Dict[str, Partition]
    manifest: SplitManifest
    extractor_name: str
    cache_metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def train(self) -> Partition:
        return self.partitions["train"]

    @property
    def validation(self) -> Partition:
        return self.partitions["validation"]

    @property
    def test(self) -> Partition:
        return self.partitions["test"]

    def xy(self, name: str) -> Tuple[np.ndarray, np.ndarray]:
        """``(features, labels)`` for one partition."""
        partition = self.partitions[name]
        if partition.features is None:
            raise PartitionError(f"Partition {name!r} was not transformed.")
        return partition.features, partition.labels

    def summary(self) -> Dict[str, Any]:
        return {
            "extractor": self.extractor_name,
            "feature_mode": self.pipeline.feature_mode,
            "n_qubits": self.pipeline.n_qubits,
            "quantum_dimension": self.pipeline.quantum_dimension,
            "n_reduced_features": self.pipeline.reduced_dimension,
            "explained_variance_ratio": round(
                self.pipeline.reducer.total_explained_variance_ratio, 6
            ),
            "split_seed": self.manifest.seed,
            "positive_classes": list(self.manifest.positive_classes),
            "partitions": [self.partitions[name].summary() for name in PARTITIONS],
        }


def load_partitions(
    *,
    extractor_name: str = "handcrafted_lab",
    config: Optional[Settings] = None,
    feature_mode: Optional[str] = None,
    n_qubits: Optional[int] = None,
    pipeline: Optional[ClassicalPipeline] = None,
    index: Optional[SmartOmIndex] = None,
    transform: bool = True,
) -> LoadedDataset:
    """Build fitted partition matrices from the cached descriptors.

    Args:
        extractor_name: which feature cache to read.
        config: settings override.
        feature_mode: ``image_only`` / ``clinical_only`` / ``multimodal``. Overrides
            the configured mode, for the PART 16 ablations.
        n_qubits: overrides the configured qubit count, which sets the reduction
            target dimension.
        pipeline: an already-fitted pipeline, e.g. one loaded from an artifact.
            When given, it is used as-is and **not** refitted -- required for
            evaluation, where refitting would change the model being evaluated.
        index: a prebuilt dataset index, to avoid re-walking the tree.
        transform: set ``False`` to skip fusion and reduction and get only the raw
            cached descriptors.

    Raises:
        PartitionError: cache and manifest disagree, or a partition is empty.
    """
    cfg = config or default_settings
    store = ArtifactStore.from_settings(cfg)

    cache = load_feature_cache(store.feature_cache_path(extractor_name))
    manifest = SplitManifest.load(store.split_manifest_path)
    dataset_index = index if index is not None else build_index(cfg.DATASET_ROOT)
    records: Dict[str, ImageRecord] = {
        record.image_id: record for record in dataset_index.records
    }

    # Verified on every load, not only when the manifest is written.
    manifest.assert_no_patient_leakage(dataset_index.records)

    image_ids: List[str] = list(cache["image_ids"])
    matrix = np.asarray(cache["matrix"], dtype=np.float64)
    if matrix.shape[0] != len(image_ids):
        raise PartitionError(
            f"Feature cache is inconsistent: {matrix.shape[0]} rows for "
            f"{len(image_ids)} image ids."
        )

    missing_from_index = [image_id for image_id in image_ids if image_id not in records]
    if missing_from_index:
        raise PartitionError(
            f"{len(missing_from_index)} cached images are absent from the dataset "
            f"index (first: {missing_from_index[0]}). The cache is stale -- rerun "
            "`python -m backend.training.prepare_dataset`."
        )
    missing_from_manifest = [
        image_id for image_id in image_ids if image_id not in manifest.image_to_partition
    ]
    if missing_from_manifest:
        raise PartitionError(
            f"{len(missing_from_manifest)} cached images are absent from the split "
            f"manifest (first: {missing_from_manifest[0]}). The cache and the "
            "manifest were generated from different dataset states."
        )

    grouped: Dict[str, List[int]] = {name: [] for name in PARTITIONS}
    for position, image_id in enumerate(image_ids):
        partition_name = manifest.image_to_partition[image_id]
        if partition_name in grouped:
            grouped[partition_name].append(position)

    partitions: Dict[str, Partition] = {}
    for name, positions in grouped.items():
        if not positions:
            raise PartitionError(
                f"Partition {name!r} is empty. Regenerate the split manifest."
            )
        rows = np.asarray(positions, dtype=int)
        ids = [image_ids[position] for position in rows]
        partitions[name] = Partition(
            name=name,
            image_ids=ids,
            patient_ids=[records[image_id].patient_id for image_id in ids],
            labels=np.asarray(
                [
                    binary_label(records[image_id].diagnostic_class, manifest.positive_classes)
                    for image_id in ids
                ],
                dtype=int,
            ),
            image_features=matrix[rows],
            clinical_rows=[
                clinical_row_for(dataset_index, records[image_id]) for image_id in ids
            ],
            diagnostic_classes=[records[image_id].diagnostic_class for image_id in ids],
        )

    active_pipeline = pipeline
    if active_pipeline is None:
        active_pipeline = build_pipeline(
            config=cfg,
            feature_mode=feature_mode,
            extractor_name=extractor_name,
            n_qubits=n_qubits,
        )
        if transform:
            train = partitions["train"]
            # The single most important line in this module: fitted on train only.
            active_pipeline.fit(
                image_features=train.image_features if active_pipeline.fusion.uses_image else None,
                clinical_rows=train.clinical_rows,
            )
    elif not active_pipeline.fitted and transform:
        raise PartitionError(
            "The supplied pipeline is not fitted, and refitting a caller-supplied "
            "pipeline would silently change the model. Fit it first, or pass "
            "pipeline=None to have one fitted on the training partition."
        )

    if transform:
        for partition in partitions.values():
            partition.features = active_pipeline.transform_matrix(
                image_features=(
                    partition.image_features if active_pipeline.fusion.uses_image else None
                ),
                clinical_rows=partition.clinical_rows,
            )

    dataset = LoadedDataset(
        pipeline=active_pipeline,
        partitions=partitions,
        manifest=manifest,
        extractor_name=extractor_name,
        cache_metadata={
            key: value
            for key, value in cache.items()
            if key not in {"matrix", "image_ids", "feature_names", "roi_fractions", "roi_sources"}
        },
    )
    logger.info(
        "Loaded %s: train %d/%d+, validation %d/%d+, test %d/%d+ | %s reduced features",
        extractor_name,
        dataset.train.n,
        dataset.train.n_positive,
        dataset.validation.n,
        dataset.validation.n_positive,
        dataset.test.n,
        dataset.test.n_positive,
        None if dataset.train.features is None else dataset.train.features.shape[1],
    )
    return dataset


def patient_groups(partition: Partition) -> np.ndarray:
    """Patient index per row, for grouped cross-validation within a partition.

    Cross-validating a baseline inside the training partition still has to respect
    patient boundaries: two images of the same patient in different folds leaks
    just as effectively as across partitions, only less visibly.
    """
    lookup: Dict[str, int] = {}
    groups = np.empty(partition.n, dtype=int)
    for position, patient_id in enumerate(partition.patient_ids):
        groups[position] = lookup.setdefault(patient_id, len(lookup))
    return groups


def class_balance(partition: Partition) -> Dict[str, int]:
    """Diagnostic-class counts, for reporting what a partition actually contains."""
    counts: Dict[str, int] = {}
    for diagnostic_class in partition.diagnostic_classes:
        counts[diagnostic_class] = counts.get(diagnostic_class, 0) + 1
    return dict(sorted(counts.items()))
